image: docker:latest

services:
  - docker:dind

stages:
  - build
  
before_script:
  - docker login -u anvibo -p $DOCKERHUB_PWD docker.io
  
build:
  stage: build
  script:
    - docker build --pull -t anvibo/baseimage .
    - docker push anvibo/baseimage:latest

        