image: docker:latest

services:
  - docker:dind

stages:
  - build
  
before_script:
  - docker login -u anvibo -p $DOCKERHUB_PWD docker.io
  
build-18.04:
  stage: build
  script:
    - docker build --pull -t anvibo/baseimage .
    - docker tag anvibo/baseimage anvibo/baseimage:18.04
    
    - docker push anvibo/baseimage:latest
    - docker push anvibo/baseimage:18.04

        
build-14.04:
  stage: build
  script:
    - docker build --pull -t anvibo/baseimage:14.04 -f Dockerfile-14.04 .
    
    - docker push anvibo/baseimage:14.04
