version: 2
jobs:
  build:
    working_directory: /docker-baseimage
    docker:
      - image: docker
    steps:
      - checkout
      - run:
          name: Build Docker image
          command: cp install-clean 18.04
        