version: 2
jobs:
  build:
    working_directory: /docker-baseimage
    docker:
      - image: docker
    steps:
      - checkout
      - run:
        name: copy install-clean script to 18.04
        command: cp install-clean 18.04
      - run:
        name: copy install-clean script to 14.04
        command: cp install-clean 14.04
      