version: 2
jobs:
  build:
    working_directory: ~/docker-baseimage/18.04
    docker:
      - image: docker
    steps:
      - checkout:
          path: ~/docker-baseimage
      - setup_remote_docker
      - run:
          name: copy install-clean script
          command: cp ../install-clean .
      - run:
          name: build docker image with tag 18.04
          command: |
            docker build -t anvibo/baseimage:18.04 .
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push anvibo/baseimage:18.04
        